services:

  db:
    image: mysql
    container_name: db_todo
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_todo
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev
  www:
    build: php
    container_name: www_todo
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
#      - ./api:/var/www
#enlever api si projet pas encore créé
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:

